FROM node:lts-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json package.json
RUN yarn

RUN apk --update --no-cache add curl

COPY src src
COPY public public
COPY tsconfig.json tsconfig.json
COPY codegen.ts codegen.ts
COPY next.config.mjs next.config.mjs

CMD npm run dev & npm run generate