services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - "./backend/src:/app/src"
      - "./backend/sportParkour.sqlite:/app/sportParkour.sqlite"
    env_file:
      - ./.env
      - ./.env
    healthcheck:
      test:
        - CMD-SHELL
        - "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./.env

  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d sportParkour -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - gcdatabase:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  gcdatabase:
